# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788df5b903aa4f8455b22212197fcc26cfdd967aa95776eec326436d25bcbef8850e92cd31bd1f2353bffd4b94a21c5b6bd4efeded4dcd0b8978b8bacd5a53dd

test:
  secret_key_base: 555a74b738c35a798760ad12e6a35f3f2b24425510116f5446e1023dbd7045d2104ec57208683bd33a518349cb8bba6bb94dd926e30d4b5fdf54a8762816c4f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
